### ISSUE TITLE
youtube-dl works on WSL-Programs

### ISSUE THREAD

**Issue by francesco1119** [ethanhs/WSL-Programs#68]
Checked today and it works

**Comment by ArsalanDotMe** [comment]
It does not. I seem to be getting this error.

```
[youtube] eH4F1Tdb040: Downloading webpage
[youtube] eH4F1Tdb040: Downloading video info webpage
[youtube] eH4F1Tdb040: Extracting video information
ERROR: Signature extraction failed: Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 905, in _decrypt_signature
    video_id, player_url, s
  File "/usr/lib/python2.7/dist-packages/youtube_dl/extractor/youtube.py", line 797, in _extract_signature_function
    raise ExtractorError('Cannot identify player %r' % player_url)
ExtractorError: Cannot identify player u'/yts/jsbin/player-vflPHG8dr/en_US/base.js'; please report this issue on https:/
/yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be sure to
 call youtube-dl with the --verbose flag and include its complete output.
 (caused by ExtractorError(u"Cannot identify player u'/yts/jsbin/player-vflPHG8dr/en_US/base.js'; please report this iss
ue on https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to updat
e. Be sure to call youtube-dl with the --verbose flag and include its complete output.",)); please report this issue on
https://yt-dl.org/bug . Make sure you are using the latest version; see  https://yt-dl.org/update  on how to update. Be
sure to call youtube-dl with the --verbose flag and include its complete output.
```

**Comment by Krutonium** [comment]
Youtube-dl works
```
krutonium@DESKTOP-JA7BBK9:/mnt/c/Users/pfckr/penguinV$ youtube-dl https://www.youtube.com/watch?v=oyUz6Ijl_wM
[youtube] oyUz6Ijl_wM: Downloading webpage
[youtube] oyUz6Ijl_wM: Downloading video info webpage
[youtube] oyUz6Ijl_wM: Extracting video information
[youtube] oyUz6Ijl_wM: Downloading MPD manifest
[download] Destination: Confinement Ep3 - The Robot-oyUz6Ijl_wM.mp4
[download] 100% of 24.75MiB in 00:10
```

**Comment by emmatyping** [comment]
Could you fix the merge conflict on your PR? Then I'd be happy to merge.

**Comment by Krutonium** [comment]
This should be closed now
